## Top 8 Powerful Functions in Python for Deeper Data Analysis

1. Groupby
2. Pivot_table
3. Aggregate
4. cross_tab
5. concat
6. apply
7. lambda
8. del(keyword)

## Groupby Function

In [78]:
import pandas as pd
insurance_data=pd.read_csv("insurance.csv")
insurance_data

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

#### 1.1 Perform Initial analysis

In [5]:
insurance_data.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [6]:
insurance_data.dtypes

age           int64
sex             str
bmi         float64
children      int64
smoker          str
region          str
charges     float64
dtype: object

In [7]:
insurance_data.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

### 1.2 Pull up the avg insurance charges based on region

In [14]:
insurance_data["region"].unique()

<StringArray>
['southwest', 'southeast', 'northwest', 'northeast']
Length: 4, dtype: str

In [22]:
insurance_data.groupby(by="region")["charges"].mean().sort_values(ascending=False).round(2) #CHAIN METHODS

region
southeast    14735.41
northeast    13406.38
northwest    12417.58
southwest    12346.94
Name: charges, dtype: float64

### 1.2 Pull up the avg insurance based on region and sex

### Discrete and continuous data
* Discrete/categorical data - countable/can't be segmented
* Continuous - Measurable and have units/can also be segmented

In [25]:
insurance_data.groupby(by=["region","sex"])["charges"].max().sort_values(ascending=False).round(2) #CHAIN METHODS

region     sex
southeast  female    63770.43
           male      62592.87
northwest  male      60021.40
northeast  female    58571.07
northwest  female    55135.40
southwest  male      52590.83
           female    48824.45
northeast  male      48549.18
Name: charges, dtype: float64

## 2. Pivot_table

In [30]:
pd.pivot_table(  data=insurance_data,values="charges",index="region",columns=["sex","children"]).round() # pivot table used for presentable data,comparing 2 categorical features vs 1 continuous data

sex         female                                                  male  \
children         0        1        2        3        4        5        0
region
northeast   9790.0  17125.0  14523.0  13730.0  14542.0      NaN  13390.0
northwest  12584.0  11119.0  13128.0  13431.0  11024.0   8966.0   9813.0
southeast  14862.0   9870.0  11766.0  19723.0  18267.0   9924.0  13792.0
southwest  10150.0  10842.0  16230.0   8439.0  10946.0  10024.0  13727.0

sex
children         1        2        3        4        5
region
northeast  15474.0  12318.0  14935.0  14442.0   6979.0
northwest   9515.0  13763.0  22971.0  11508.0      NaN
southeast  17425.0  18648.0  17102.0   8727.0  10307.0
southwest   9971.0  18876.0  12072.0  17924.0   6865.0

## 3.Aggregate

In [31]:
insurance_data.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

### 3.1 Find out the avergae insurance charges based on regions

In [ ]:
insurance_data.agg()

In [35]:
insurance_data.groupby(by="region")["charges"].mean().sort_values(ascending=False).round(2) #CHAIN METHODS

region
southeast    14735.41
northeast    13406.38
northwest    12417.58
southwest    12346.94
Name: charges, dtype: float64

In [40]:
insurance_data.groupby(by=["region","sex"])["charges"].agg(func=["mean","min","sum"]).round()

                     mean     min        sum
region    sex
northeast female  12953.0  2196.0  2085466.0
          male    13854.0  1695.0  2258203.0
northwest female  12480.0  2117.0  2046699.0
          male    12354.0  1621.0  1989013.0
southeast female  13500.0  1608.0  2362442.0
          male    15880.0  1122.0  3001248.0
southwest female  11274.0  1728.0  1826455.0
          male    13413.0  1242.0  2186300.0

## 4.CrossTab - compare two categorical data  to comeup with the frequency

In [41]:
insurance_data.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

## Note

In [57]:
insurance_data.age #if we need only one column we can use dot

0       19
1       18
2       28
3       33
4       32
        ..
1333    50
1334    18
1335    18
1336    21
1337    61
Name: age, Length: 1338, dtype: int64

### 4.1 How many smokers and non-smokers based on region?

In [43]:
pd.crosstab(index=insurance_data["region"],columns=insurance_data["smoker"],margins=True)

smoker       no  yes   All
region
northeast   257   67   324
northwest   267   58   325
southeast   273   91   364
southwest   267   58   325
All        1064  274  1338

In [ ]:
insurance_data["region"]

## 5. Concat

In [56]:
sales_data_2017=pd.read_csv("Sales Transaction 2017.csv")
sales_data_2018=pd.read_csv("Sales Transaction 2018.csv")
sales_data_2019=pd.read_csv("Sales Transaction 2019.csv")
sales_full_data=pd.concat(objs=[sales_data_2017,sales_data_2018,sales_data_2019])

### Level 4.5/5 Complexity Challenge

### merge function(explore it)--left join,right join,outer join

## 6. Apply

In [58]:
insurance_data.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

### 6.1 Create a new column in the same dataframe with the name "Eligibility Criteria" where if age is > 20,say Eligible else not

In [64]:
def get_age(x):
    if x>20:
        return "Eligible"
    else:
        return "Not Eligible"

In [66]:
insurance_data["Eligibility Criteria"]=insurance_data["age"].apply(get_age)
insurance_data

,age,sex,bmi,children,smoker,region,charges,Eligibility Criteria
0,19,female,27.900,0,yes,southwest,16884.92400,Not Eligible
1,18,male,33.770,1,no,southeast,1725.55230,Not Eligible
2,28,male,33.000,3,no,southeast,4449.46200,Eligible
3,33,male,22.705,0,no,northwest,21984.47061,Eligible
4,32,male,28.880,0,no,northwest,3866.85520,Eligible
...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,Eligible
1334,18,female,31.920,0,no,northeast,2205.98080,Not Eligible
1335,18,female,36.850,0,no,southeast,1629.83350,Not Eligible
1336,21,female,25.800,0,no,southwest,2007.94500,Eligible
1337,61,female,29.070,0,yes,northwest,29141.36030,Eligible

## 7.lambda function

* Anonymous function/nameless function

In [85]:
insurance_data["EC"]=insurance_data["age"].apply(lambda x:"ELigible" if x>20 else "NE")
insurance_data

      age     sex     bmi  children smoker     region      charges        EC
0      19  female  27.900         0    yes  southwest  16884.92400        NE
1      18    male  33.770         1     no  southeast   1725.55230        NE
2      28    male  33.000         3     no  southeast   4449.46200  ELigible
3      33    male  22.705         0     no  northwest  21984.47061  ELigible
4      32    male  28.880         0     no  northwest   3866.85520  ELigible
...   ...     ...     ...       ...    ...        ...          ...       ...
1333   50    male  30.970         3     no  northwest  10600.54830  ELigible
1334   18  female  31.920         0     no  northeast   2205.98080        NE
1335   18  female  36.850         0     no  southeast   1629.83350        NE
1336   21  female  25.800         0     no  southwest   2007.94500  ELigible
1337   61  female  29.070         0    yes  northwest  29141.36030  ELigible

[1338 rows x 8 columns]

### Explore List Comprehension(3 examples)

### Explore lambda-map,filter,reduce

## 8. Del Keyword

In [86]:
insurance_data

      age     sex     bmi  children smoker     region      charges        EC
0      19  female  27.900         0    yes  southwest  16884.92400        NE
1      18    male  33.770         1     no  southeast   1725.55230        NE
2      28    male  33.000         3     no  southeast   4449.46200  ELigible
3      33    male  22.705         0     no  northwest  21984.47061  ELigible
4      32    male  28.880         0     no  northwest   3866.85520  ELigible
...   ...     ...     ...       ...    ...        ...          ...       ...
1333   50    male  30.970         3     no  northwest  10600.54830  ELigible
1334   18  female  31.920         0     no  northeast   2205.98080        NE
1335   18  female  36.850         0     no  southeast   1629.83350        NE
1336   21  female  25.800         0     no  southwest   2007.94500  ELigible
1337   61  female  29.070         0    yes  northwest  29141.36030  ELigible

[1338 rows x 8 columns]

In [87]:
del insurance_data["EC"]  #del insurance_data.EC (here the dot won't )
insurance_data

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

## THE END