# Task1 Data Cleaning

In [174]:
import pandas as pd
sales_data_2017=pd.read_csv("Sales Transaction 2017.csv")
sales_data_2018=pd.read_csv("Sales Transaction 2018.csv")
sales_data_2019=pd.read_csv("Sales Transaction 2019.csv")

sales_full_list=pd.concat(objs=[sales_data_2017,sales_data_2018,sales_data_2019])

sales_full_list["Date"]=sales_full_list["Date"].str.strip() 
sales_full_list=sales_full_list.dropna(subset=["Date"]) 
sales_full_list["Date"]=pd.to_datetime(sales_full_list["Date"],dayfirst=True)

sales_full_list=sales_full_list.dropna(subset=["Voucher"])
sales_full_list=sales_full_list[sales_full_list["Voucher"].str.contains("Sal:",na=False)]
sales_full_list["Voucher"]=sales_full_list["Voucher"].str.strip().str.replace("Sal:","",regex=False).astype(int)
sales_full_list["Qty"]=sales_full_list["Qty"].str.strip().str.replace(",","",regex=False).astype(float).astype(int)
sales_full_list=sales_full_list.dropna(subset=["Rate"])
sales_full_list["Rate"]=sales_full_list["Rate"].str.strip().str.replace(",","",regex=False).astype(float)
sales_full_list=sales_full_list.dropna(subset=["Gross"])
sales_full_list["Gross"]=sales_full_list["Gross"].str.strip().str.replace(",","",regex=False).astype(float)
sales_full_list["Disc"]=sales_full_list["Disc"].fillna("0")
sales_full_list["Disc"]=sales_full_list["Disc"].str.strip().str.replace(",","",regex=False).astype(float)
sales_full_list["Voucher Amount"]=sales_full_list["Voucher Amount"].fillna("0")
sales_full_list["Voucher Amount"]=sales_full_list["Voucher Amount"].str.strip().str.replace(",","",regex=False).astype(float)
sales_full_list

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,2017-04-01,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0,3380.0,0.0,13100.0
1,2017-04-01,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0,9720.0,0.0,0.0
2,2017-04-01,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0,11500.0,0.0,30990.0
3,2017-04-01,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0,9720.0,0.0,0.0
4,2017-04-01,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0,8450.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
19167,2019-10-10,4935,K.SRIHARI,16*20(100-W),140,26.0,3640.0,0.0,0.0
19168,2019-10-10,4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4,5040.0,0.0,0.0
19169,2019-10-10,4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16.0,5120.0,0.0,0.0
19170,2019-10-10,4935,K.SRIHARI,10*12 RK,800,8.5,6800.0,0.0,0.0
19171,2019-10-10,4935,K.SRIHARI,13*16 WHITE RK,400,16.0,6400.0,0.0,0.0

In [175]:
sales_full_list.dtypes

Date              datetime64[us]
Voucher                    int64
Party                        str
Product                      str
Qty                        int64
Rate                     float64
Gross                    float64
Disc                     float64
Voucher Amount           float64
dtype: object

In [176]:
sales_full_list.info()

<class 'pandas.DataFrame'>
Index: 95561 entries, 0 to 19171
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            95561 non-null  datetime64[us]
 1   Voucher         95561 non-null  int64
 2   Party           95561 non-null  str
 3   Product         95561 non-null  str
 4   Qty             95561 non-null  int64
 5   Rate            95561 non-null  float64
 6   Gross           95561 non-null  float64
 7   Disc            95561 non-null  float64
 8   Voucher Amount  95561 non-null  float64
dtypes: datetime64[us](1), float64(4), int64(2), str(2)
memory usage: 7.3 MB

# Task 1-->Rough Work of Data Cleaning

In [58]:
sales_full_list

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
19169,10/10/2019,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16,"5,120.00",NaN,NaN
19170,10/10/2019,Sal:4935,K.SRIHARI,10*12 RK,800,8.5,"6,800.00",NaN,NaN
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN
19174,NaN,Total,NaN,NaN,"99,284.90","175,381.65","2,203,649.50","20,680.00","2,189,014.50"
19175,NaN,Total,NaN,NaN,"2,710,193.00","5,519,888.40","53,360,791.40","672,984.00","52,830,224.40"

In [88]:
sales_full_list=sales_full_list[sales_full_list["Voucher"].str.contains("Sal:",na=False)]
sales_full_list

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,Sal:1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,Sal:1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,Sal:2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,Sal:2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,Sal:2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
19167,10/10/2019,Sal:4935,K.SRIHARI,16*20(100-W),140,26,"3,640.00",NaN,NaN
19168,10/10/2019,Sal:4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4,"5,040.00",NaN,NaN
19169,10/10/2019,Sal:4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16,"5,120.00",NaN,NaN
19170,10/10/2019,Sal:4935,K.SRIHARI,10*12 RK,800,8.5,"6,800.00",NaN,NaN
19171,10/10/2019,Sal:4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN

In [89]:
sales_full_list["Voucher"]=sales_full_list["Voucher"].str.strip().str.replace("Sal:","",regex=False).astype(int)

In [90]:
sales_full_list

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
19167,10/10/2019,4935,K.SRIHARI,16*20(100-W),140,26,"3,640.00",NaN,NaN
19168,10/10/2019,4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4,"5,040.00",NaN,NaN
19169,10/10/2019,4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16,"5,120.00",NaN,NaN
19170,10/10/2019,4935,K.SRIHARI,10*12 RK,800,8.5,"6,800.00",NaN,NaN
19171,10/10/2019,4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN

In [94]:
sales_full_list.dtypes

Date                str
Voucher           int64
Party               str
Product             str
Qty               int64
Rate                str
Gross               str
Disc                str
Voucher Amount      str
dtype: object

In [71]:
sales_full_list["Qty"].isnull().sum()

np.int64(0)

In [92]:
sales_full_list["Qty"]=sales_full_list["Qty"].str.strip().str.replace(",","",regex=False).astype(float).astype(int)

In [93]:
sales_full_list

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
19167,10/10/2019,4935,K.SRIHARI,16*20(100-W),140,26,"3,640.00",NaN,NaN
19168,10/10/2019,4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4,"5,040.00",NaN,NaN
19169,10/10/2019,4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16,"5,120.00",NaN,NaN
19170,10/10/2019,4935,K.SRIHARI,10*12 RK,800,8.5,"6,800.00",NaN,NaN
19171,10/10/2019,4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN

In [103]:
sales_full_list=sales_full_list.dropna(subset=["Rate"])

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,1,SOLANKI PLASTICS,DONA-VAI-9100,2,"1,690.00","3,380.00",NaN,"13,100.00"
1,1/4/2017,1,SOLANKI PLASTICS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
2,1/4/2017,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23,"11,500.00",NaN,"30,990.00"
3,1/4/2017,2,SARNESWARA TRADERS,LITE FOAM(1200),6,"1,620.00","9,720.00",NaN,NaN
4,1/4/2017,2,SARNESWARA TRADERS,DONA-VAI-9100,5,"1,690.00","8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
19167,10/10/2019,4935,K.SRIHARI,16*20(100-W),140,26,"3,640.00",NaN,NaN
19168,10/10/2019,4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4,"5,040.00",NaN,NaN
19169,10/10/2019,4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16,"5,120.00",NaN,NaN
19170,10/10/2019,4935,K.SRIHARI,10*12 RK,800,8.5,"6,800.00",NaN,NaN
19171,10/10/2019,4935,K.SRIHARI,13*16 WHITE RK,400,16,"6,400.00",NaN,NaN

In [108]:
sales_full_list["Rate"]=sales_full_list["Rate"].str.strip().str.replace(",","",regex=False).astype(float)

AttributeError: Can only use .str accessor with string values, not floating

In [109]:
sales_full_list

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0,"3,380.00",NaN,"13,100.00"
1,1/4/2017,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0,"9,720.00",NaN,NaN
2,1/4/2017,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0,"11,500.00",NaN,"30,990.00"
3,1/4/2017,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0,"9,720.00",NaN,NaN
4,1/4/2017,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0,"8,450.00",NaN,NaN
...,...,...,...,...,...,...,...,...,...
19167,10/10/2019,4935,K.SRIHARI,16*20(100-W),140,26.0,"3,640.00",NaN,NaN
19168,10/10/2019,4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4,"5,040.00",NaN,NaN
19169,10/10/2019,4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16.0,"5,120.00",NaN,NaN
19170,10/10/2019,4935,K.SRIHARI,10*12 RK,800,8.5,"6,800.00",NaN,NaN
19171,10/10/2019,4935,K.SRIHARI,13*16 WHITE RK,400,16.0,"6,400.00",NaN,NaN

In [122]:
sales_full_list=sales_full_list.dropna(subset=["Gross"])

In [113]:
sales_full_list["Gross"]=sales_full_list["Gross"].str.strip().str.replace(",","",regex=False).astype(float)

In [114]:
sales_full_list

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
0,1/4/2017,1,SOLANKI PLASTICS,DONA-VAI-9100,2,1690.0,3380.0,NaN,"13,100.00"
1,1/4/2017,1,SOLANKI PLASTICS,LITE FOAM(1200),6,1620.0,9720.0,NaN,NaN
2,1/4/2017,2,SARNESWARA TRADERS,VISHNU CHOTA WINE,500,23.0,11500.0,NaN,"30,990.00"
3,1/4/2017,2,SARNESWARA TRADERS,LITE FOAM(1200),6,1620.0,9720.0,NaN,NaN
4,1/4/2017,2,SARNESWARA TRADERS,DONA-VAI-9100,5,1690.0,8450.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...
19167,10/10/2019,4935,K.SRIHARI,16*20(100-W),140,26.0,3640.0,NaN,NaN
19168,10/10/2019,4935,K.SRIHARI,10*12 KRISHNA-BK(10,600,8.4,5040.0,NaN,NaN
19169,10/10/2019,4935,K.SRIHARI,13*16 Bk(100)KRISHN,320,16.0,5120.0,NaN,NaN
19170,10/10/2019,4935,K.SRIHARI,10*12 RK,800,8.5,6800.0,NaN,NaN
19171,10/10/2019,4935,K.SRIHARI,13*16 WHITE RK,400,16.0,6400.0,NaN,NaN

In [128]:
sales_full_list=sales_full_list.dropna(subset=["Disc"])

In [126]:
sales_full_list["Disc"]=sales_full_list["Disc"].str.strip().str.replace(",","",regex=False).astype(float)

AttributeError: Can only use .str accessor with string values, not floating

In [129]:
sales_full_list

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
6,1/4/2017,898,Lock,Vishnu 250ml,100,30.00,3000.0,100.0,"5,400.00"
7,1/4/2017,898,Lock,BLACK DOG-350ML,100,26.00,2600.0,100.0,NaN
85,3/4/2017,22,KPR,4*5 MEET,20,14.50,290.0,290.0,NaN
94,3/4/2017,24,SVP-BUCHHI,14 GREEN,6000,1.30,7800.0,50.0,"8,710.00"
120,3/4/2017,29,Vlp,NAPKEEN 2ND,375,9.00,3375.0,3375.0,NaN
...,...,...,...,...,...,...,...,...,...
18786,7/10/2019,4838,Gv,NON WOVEN 10*14,120,80.00,9600.0,9600.0,NaN
18899,9/10/2019,4855,JAGADHAMBA PLASTICS,LITE FOAM(1200),3,1680.00,5040.0,150.0,"4,890.00"
18944,9/10/2019,4865,SVP-BUCHHI,5*6 ANKIT(20MIC),10,23.00,230.0,230.0,NaN
19012,9/10/2019,4892,Srinu,SILV-CONT-450ML(150,1,2350.00,2350.0,2350.0,NaN
19135,10/10/2019,4925,SLST-GDR,500ML PLASTIC BOULS,1000,3.55,3550.0,3550.0,"4,090.00"

In [132]:
sales_full_list["Voucher Amount"].isnull().sum()

np.int64(2269)

In [134]:
sales_full_list=sales_full_list.dropna(subset=["Voucher Amount"])
sales_full_list["Voucher Amount"]=sales_full_list["Voucher Amount"].str.strip().str.replace(",","",regex=False).astype(float)

In [135]:
sales_full_list["Voucher Amount"]=sales_full_list["Voucher Amount"].str.strip().str.replace(",","",regex=False).astype(float)

In [136]:
sales_full_list

,Date,Voucher,Party,Product,Qty,Rate,Gross,Disc,Voucher Amount
6,1/4/2017,898,Lock,Vishnu 250ml,100,30.00,3000.0,100.0,5400.0
94,3/4/2017,24,SVP-BUCHHI,14 GREEN,6000,1.30,7800.0,50.0,8710.0
324,4/4/2017,102,KPR,BLACK DOG-350ML,100,25.00,2500.0,50.0,2450.0
357,5/4/2017,67,SRI JYOTHI TRADERS,LITE FOAM(1200),14,1620.00,22680.0,560.0,38180.0
589,6/4/2017,109,SVP-BUCHHI,10*12 SARAS-NAT,1500,8.10,12150.0,12150.0,23105.0
...,...,...,...,...,...,...,...,...,...
17175,17/09/2019,4402,K.SRIHARI,SMART BOUL(48),1,1830.00,1830.0,310.0,5270.0
17382,19/09/2019,4456,Svr,NO-0,25,150.00,3750.0,3750.0,20.0
17744,24/09/2019,4549,LT,GANGA 13*16 100 B,300,12.00,3600.0,3600.0,6865.0
18899,9/10/2019,4855,JAGADHAMBA PLASTICS,LITE FOAM(1200),3,1680.00,5040.0,150.0,4890.0
19135,10/10/2019,4925,SLST-GDR,500ML PLASTIC BOULS,1000,3.55,3550.0,3550.0,4090.0

In [140]:
sales_full_list["Product"].isnull().sum()

np.int64(0)

# Task 2 - Merge Function 1 Example

## Inner Join -- (if how is not used it automatically consider it as inner join)

In [192]:
import pandas as pd
employee_data=pd.read_csv("employee_data.csv")
empdata=pd.read_csv("empdata.csv")
pd.merge(employee_data,empdata,on="Name")

,Name,Age_x,Department_x,Salary,Join_Date,Age_y,Department_y,Ph No,Emp_ID
0,Rajesh,29.0,Ops,60000.0,21-05-2023,29,Ops,9456879631,Ops-6321
1,Nasir,31.0,IT Tech,NaN,12-11-2020,31,IT Tech,6345978341,IT Tech-6891
2,Gilbert,29.0,Ops,60000.0,21-05-2021,29,Ops,9875361456,Ops-6789
3,Kevin,28.0,Support,61000.0,30-07-2024,28,Support,6398753156,Support-9864
4,Navin,35.0,Support,72000.0,19-08-2023,35,Support,9875320465,Support-6782
5,Nasir,31.0,IT Tech,NaN,12-11-2020,31,IT Tech,6345978341,IT Tech-6891

## Right Join

In [196]:
pd.merge(employee_data,empdata,on="Age",how="right")

,Name_x,Age,Department_x,Salary,Join_Date,Name_y,Department_y,Ph No,Emp_ID
0,Rajesh,29.0,Ops,60000.0,21-05-2023,Rajesh,Ops,9456879631,Ops-6321
1,Gilbert,29.0,Ops,60000.0,21-05-2021,Rajesh,Ops,9456879631,Ops-6321
2,Nasir,31.0,IT Tech,NaN,12-11-2020,Nasir,IT Tech,6345978341,IT Tech-6891
3,Nasir,31.0,IT Tech,NaN,12-11-2020,Nasir,IT Tech,6345978341,IT Tech-6891
4,NaN,36.0,NaN,NaN,NaN,Mathew,Support,9845632144,Support-6964
5,Rajesh,29.0,Ops,60000.0,21-05-2023,Gilbert,Ops,9875361456,Ops-6789
6,Gilbert,29.0,Ops,60000.0,21-05-2021,Gilbert,Ops,9875361456,Ops-6789
7,Kevin,28.0,Support,61000.0,30-07-2024,Kevin,Support,6398753156,Support-9864
8,Navin,35.0,Support,72000.0,19-08-2023,Navin,Support,9875320465,Support-6782
9,NaN,40.0,IT,64000.0,10-09-2022,Steve,IT Tech,9634587961,IT Tech-6783
10,Nasir,31.0,IT Tech,NaN,12-11-2020,Ben,IT Tech,6459872361,IT Tech-6456
11,Nasir,31.0,IT Tech,NaN,12-11-2020,Ben,IT Tech,6459872361,IT Tech-6456

## Left Join

In [197]:
pd.merge(employee_data,empdata,on="Age",how="left")

,Name_x,Age,Department_x,Salary,Join_Date,Name_y,Department_y,Ph No,Emp_ID
0,Rajesh,29.0,Ops,60000.0,21-05-2023,Rajesh,Ops,9.456880e+09,Ops-6321
1,Rajesh,29.0,Ops,60000.0,21-05-2023,Gilbert,Ops,9.875361e+09,Ops-6789
2,Nasir,31.0,IT Tech,NaN,12-11-2020,Nasir,IT Tech,6.345978e+09,IT Tech-6891
3,Nasir,31.0,IT Tech,NaN,12-11-2020,Ben,IT Tech,6.459872e+09,IT Tech-6456
4,Mathiew,NaN,Support,58000.0,15-01-2025,NaN,NaN,NaN,NaN
5,Gilbert,29.0,Ops,60000.0,21-05-2021,Rajesh,Ops,9.456880e+09,Ops-6321
6,Gilbert,29.0,Ops,60000.0,21-05-2021,Gilbert,Ops,9.875361e+09,Ops-6789
7,Kevin,28.0,Support,61000.0,30-07-2024,Kevin,Support,6.398753e+09,Support-9864
8,Navin,35.0,Support,72000.0,19-08-2023,Navin,Support,9.875320e+09,Support-6782
9,NaN,40.0,IT,64000.0,10-09-2022,Steve,IT Tech,9.634588e+09,IT Tech-6783
10,Nasir,31.0,IT Tech,NaN,12-11-2020,Nasir,IT Tech,6.345978e+09,IT Tech-6891
11,Nasir,31.0,IT Tech,NaN,12-11-2020,Ben,IT Tech,6.459872e+09,IT Tech-6456

# Task 3 List Comprehension 2 examples

In [199]:
even=[i for i in range(1,10) if i%2==0]
even

[2, 4, 6, 8]

In [202]:
Country=["India","Scotland","Norway"]
Upper=[p.upper() for p in Country]
Upper

['INDIA', 'SCOTLAND', 'NORWAY']

# Task 4 -- Lambda Function 2 examples with Map, Filter, Reduce

In [208]:
import pandas as pd
insurance_details=pd.read_csv("insurance.csv")
insurance_details

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

## Map -- (Modify All)

In [213]:
insurance_details["Criteria"] = list(map(lambda x: "Eligible" if x > 20 else "NA",insurance_details["age"]))

In [214]:
insurance_details

      age     sex     bmi  children smoker     region      charges  Criteria
0      19  female  27.900         0    yes  southwest  16884.92400        NA
1      18    male  33.770         1     no  southeast   1725.55230        NA
2      28    male  33.000         3     no  southeast   4449.46200  Eligible
3      33    male  22.705         0     no  northwest  21984.47061  Eligible
4      32    male  28.880         0     no  northwest   3866.85520  Eligible
...   ...     ...     ...       ...    ...        ...          ...       ...
1333   50    male  30.970         3     no  northwest  10600.54830  Eligible
1334   18  female  31.920         0     no  northeast   2205.98080        NA
1335   18  female  36.850         0     no  southeast   1629.83350        NA
1336   21  female  25.800         0     no  southwest   2007.94500  Eligible
1337   61  female  29.070         0    yes  northwest  29141.36030  Eligible

[1338 rows x 8 columns]

## filter

In [217]:
eligible_age=list(filter(lambda x:x>20,insurance_details["age"]))
eligible_age

[28,
 33,
 32,
 31,
 46,
 37,
 37,
 60,
 25,
 62,
 23,
 56,
 27,
 52,
 23,
 56,
 30,
 60,
 30,
 34,
 37,
 59,
 63,
 55,
 23,
 31,
 22,
 63,
 28,
 62,
 26,
 35,
 60,
 24,
 31,
 41,
 37,
 38,
 55,
 28,
 60,
 36,
 21,
 48,
 36,
 40,
 58,
 58,
 53,
 34,
 43,
 25,
 64,
 28,
 61,
 40,
 40,
 28,
 27,
 31,
 53,
 58,
 44,
 57,
 29,
 21,
 22,
 41,
 31,
 45,
 22,
 48,
 37,
 45,
 57,
 56,
 46,
 55,
 21,
 53,
 59,
 35,
 64,
 28,
 54,
 55,
 56,
 38,
 41,
 30,
 61,
 34,
 26,
 29,
 63,
 54,
 55,
 37,
 21,
 52,
 60,
 58,
 29,
 49,
 37,
 44,
 44,
 47,
 26,
 52,
 32,
 38,
 59,
 61,
 53,
 22,
 22,
 54,
 22,
 34,
 26,
 34,
 29,
 30,
 29,
 46,
 51,
 53,
 35,
 48,
 32,
 42,
 40,
 44,
 48,
 30,
 50,
 42,
 54,
 32,
 37,
 47,
 32,
 27,
 63,
 49,
 35,
 24,
 63,
 38,
 54,
 46,
 41,
 58,
 22,
 44,
 44,
 36,
 26,
 30,
 41,
 29,
 61,
 36,
 25,
 56,
 39,
 45,
 51,
 64,
 48,
 60,
 27,
 46,
 28,
 59,
 35,
 63,
 40,
 40,
 24,
 34,
 45,
 41,
 53,
 27,
 26,
 24,
 34,
 53,
 32,
 42,
 55,
 28,
 58,
 41,
 47,
 42,
 59,
 59,
 39,
 40,
 31,
 44,
 23,
 33,
 55,
 40,
 63,
 54,
 60,
 24,
 29,
 63,
 54,
 27,
 50,
 55,
 56,
 38,
 51,
 58,
 52,
 53,
 46,
 40,
 59,
 45,
 49,
 50,
 41,
 50,
 25,
 47,
 22,
 59,
 51,
 40,
 54,
 30,
 55,
 52,
 46,
 46,
 63,
 59,
 52,
 28,
 29,
 25,
 22,
 25,
 47,
 31,
 48,
 36,
 53,
 56,
 28,
 57,
 29,
 28,
 30,
 58,
 41,
 50,
 43,
 49,
 27,
 52,
 50,
 54,
 44,
 32,
 34,
 26,
 34,
 57,
 29,
 40,
 27,
 45,
 64,
 52,
 61,
 52,
 61,
 56,
 43,
 64,
 60,
 62,
 50,
 46,
 24,
 62,
 60,
 63,
 49,
 34,
 33,
 46,
 36,
 57,
 50,
 30,
 33,
 46,
 46,
 47,
 23,
 48,
 35,
 21,
 21,
 49,
 56,
 42,
 44,
 61,
 57,
 42,
 26,
 23,
 39,
 24,
 64,
 62,
 27,
 55,
 55,
 35,
 44,
 58,
 50,
 26,
 24,
 48,
 48,
 49,
 46,
 46,
 43,
 21,
 64,
 51,
 47,
 64,
 49,
 31,
 52,
 33,
 47,
 38,
 32,
 44,
 26,
 25,
 43,
 52,
 36,
 64,
 63,
 64,
 61,
 40,
 25,
 48,
 45,
 38,
 21,
 27,
 29,
 42,
 60,
 31,
 60,
 22,
 35,
 52,
 26,
 31,
 33,
 59,
 56,
 45,
 60,
 56,
 40,
 35,
 39,
 30,
 24,
 32,
 59,
 55,
 57,
 56,
 40,
 49,
 42,
 62,
 56,
 30,
 60,
 56,
 28,
 27,
 47,
 54,
 61,
 24,
 25,
 21,
 23,
 63,
 49,
 51,
 48,
 31,
 54,
 44,
 53,
 61,
 61,
 21,
 31,
 45,
 44,
 62,
 29,
 43,
 51,
 38,
 37,
 22,
 21,
 24,
 57,
 56,
 27,
 51,
 39,
 58,
 45,
 35,
 31,
 50,
 32,
 51,
 38,
 42,
 51,
 46,
 57,
 62,
 59,
 37,
 64,
 38,
 33,
 46,
 46,
 53,
 34,
 63,
 54,
 54,
 49,
 28,
 54,
 25,
 43,
 63,
 32,
 62,
 52,
 25,
 28,
 46,
 34,
 35,
 46,
 54,
 27,
 50,
 38,
 41,
 49,
 48,
 31,
 30,
 62,
 57,
 58,
 22,
 31,
 52,
 25,
 59,
 39,
 32,
 33,
 21,
 34,
 61,
 38,
 58,
 47,
 21,
 41,
 46,
 42,
 34,
 43,
 52,
 51,
 56,
 64,
 51,
 27,
 59,
 28,
 30,
 47,
 38,
 34,
 47,
 56,
 49,
 55,
 30,
 37,
 49,
 59,
 29,
 36,
 33,
 58,
 44,
 53,
 24,
 29,
 40,
 51,
 64,
 35,
 39,
 56,
 33,
 42,
 61,
 23,
 43,
 48,
 39,
 40,
 58,
 49,
 53,
 48,
 45,
 59,
 52,
 26,
 27,
 48,
 57,
 37,
 57,
 32,
 64,
 43,
 49,
 40,
 62,
 40,
 30,
 29,
 36,
 41,
 44,
 45,
 55,
 60,
 56,
 49,
 21,
 39,
 53,
 33,
 53,
 42,
 40,
 47,
 27,
 21,
 47,
 24,
 27,
 26,
 53,
 41,
 56,
 23,
 21,
 50,
 53,
 34,
 47,
 33,
 51,
 49,
 31,
 36,
 50,
 43,
 24,
 60,
 49,
 60,
 51,
 58,
 51,
 53,
 62,
 50,
 30,
 41,
 29,
 41,
 35,
 53,
 24,
 48,
 59,
 49,
 37,
 26,
 23,
 29,
 45,
 27,
 53,
 31,
 50,
 50,
 34,
 47,
 28,
 37,
 21,
 64,
 58,
 24,
 31,
 39,
 47,
 30,
 22,
 23,
 33,
 27,
 45,
 57,
 47,
 42,
 64,
 38,
 61,
 53,
 44,
 41,
 51,
 40,
 45,
 35,
 53,
 30,
 51,
 50,
 31,
 35,
 60,
 21,
 29,
 62,
 39,
 22,
 53,
 39,
 27,
 30,
 30,
 58,
 33,
 42,
 64,
 21,
 23,
 45,
 40,
 25,
 46,
 33,
 54,
 28,
 36,
 24,
 23,
 47,
 33,
 45,
 26,
 44,
 60,
 64,
 56,
 36,
 41,
 39,
 63,
 36,
 28,
 58,
 36,
 42,
 36,
 56,
 35,
 59,
 21,
 59,
 23,
 57,
 53,
 60,
 51,
 23,
 27,
 55,
 37,
 61,
 46,
 53,
 49,
 48,
 25,
 25,
 57,
 37,
 38,
 55,
 36,
 51,
 40,
 57,
 61,
 25,
 50,
 26,
 42,
 43,
 44,
 23,
 49,
 33,
 41,
 37,
 22,
 23,
 21,
 51,
 25,
 32,
 57,
 36,
 22,
 57,
 64,
 36,
 54,
 47,
 62,
 61,
 43,
 49,
 60,
 26,
 49,
 60,
 26,
 27,
 44,
 63,
 32,
 22,
 59,
 44,
 33,
 24,
 43,
 45,
 61,
 35,
 62,
 62,
 38,
 34,
 43,
 50,
 57,
 62,
 41,
 26,
 39,
 46,
 45,
 32,
 59,
 44,
 39,
 53,
 50,
 62,
 56,
 42,
 37,
 42,
 25,
 57,
 51,
 30,
 44,
 34,
 31,
 54,
 24,
 43,
 48,
 29,
 63,
 46,
 52,
 35,
 51,
 44,
 21,
 39,
 50,
 34,
 22,
 26,
 29,
 48,
 26,
 45,
 36,
 54,
 34,
 31,
 27,
 44,
 43,
 45,
 34,
 24,
 26,
 38,
 50,
 38,
 27,
 39,
 39,
 63,
 33,
 36,
 30,
 24,
 24,
 48,
 47,
 29,
 28,
 47,
 25,
 51,
 48,
 43,
 61,
 48,
 38,
 59,
 26,
 54,
 21,
 51,
 22,
 47,
 47,
 21,
 23,
 54,
 37,
 46,
 55,
 30,
 61,
 54,
 22,
 45,
 22,
 35,
 28,
 55,
 43,
 43,
 22,
 25,
 49,
 44,
 64,
 49,
 47,
 27,
 55,
 48,
 45,
 24,
 32,
 24,
 57,
 59,
 36,
 29,
 42,
 48,
 39,
 63,
 54,
 37,
 63,
 21,
 54,
 60,
 32,
 47,
 21,
 28,
 63,
 32,
 38,
 32,
 62,
 39,
 55,
 57,
 52,
 56,
 47,
 55,
 23,
 22,
 50,
 51,
 22,
 52,
 25,
 33,
 53,
 29,
 58,
 37,
 54,
 49,
 50,
 26,
 45,
 54,
 38,
 48,
 28,
 23,
 55,
 41,
 25,
 33,
 30,
 23,
 46,
 53,
 27,
 23,
 63,
 55,
 35,
 34,
 39,
 27,
 57,
 ...]

## Reduce -- combine all into one

In [219]:
from functools import reduce
total_charges=reduce(lambda x,y:x+y,insurance_details["charges"])
total_charges

17755824.990759