# Task 1

## Function example for all DataStructures

## List

### append

In [19]:
high_inflation_countries=["India","Bangladesh","Srilanka","Nepal","Myanmar",]
high_inflation_countries.append("Bhutan")  ###here the append exactly takes only one argument
high_inflation_countries

['India', 'Bangladesh', 'Srilanka', 'Nepal', 'Myanmar', 'Bhutan']

### pop

In [7]:
high_inflation_countries=["India","Bangladesh","Srilanka","Nepal","Myanmar",]
high_inflation_countries.pop(3)

'Nepal'

### count

In [8]:
high_inflation_countries=["India","Bangladesh","Srilanka","Nepal","Myanmar",]
high_inflation_countries.count("India")

1

### copy

In [13]:
high_inflation_countries=["India","Bangladesh","Srilanka","Nepal","Myanmar",]
low_developed_countries=high_inflation_countries.copy()
low_developed_countries

['India', 'Bangladesh', 'Srilanka', 'Nepal', 'Myanmar']

### clear

In [16]:
high_inflation_countries=["India","Bangladesh","Srilanka","Nepal","Myanmar",]
high_inflation_countries.clear()
print(high_inflation_countries)

[]

### extend

In [22]:
high_inflation_countries=["India","Bangladesh","Srilanka","Nepal","Myanmar",]
least_developed_countries=["Pakistan","South_Sudan","Niger"]
high_inflation_countries.extend(least_developed_countries)
print(high_inflation_countries)

['India', 'Bangladesh', 'Srilanka', 'Nepal', 'Myanmar', 'Pakistan', 'South_Sudan', 'Niger']

### index

In [26]:
high_inflation_countries=["India","Bangladesh","Srilanka","Nepal","Myanmar",]
high_inflation_countries.index("Bangladesh")

1

### insert

In [33]:
high_inflation_countries=["India","Bangladesh","Srilanka","Nepal","Myanmar",]
high_inflation_countries.insert(3,"Bhutan")  
print(high_inflation_countries)

['India', 'Bangladesh', 'Srilanka', 'Bhutan', 'Nepal', 'Myanmar']

### remove

In [35]:
high_inflation_countries=["India","Bangladesh","Srilanka","Nepal","Myanmar",]
high_inflation_countries.remove("Nepal")
print(high_inflation_countries)

['India', 'Bangladesh', 'Srilanka', 'Myanmar']

### reverse

In [67]:
high_inflation_countries=["India","Bangladesh","Srilanka","Nepal","Myanmar",]
high_inflation_countries.reverse()  ###takes no arguments
print(high_inflation_countries)

['Myanmar', 'Nepal', 'Srilanka', 'Bangladesh', 'India']

### sort

In [53]:
high_inflation_countries=["India","Bangladesh","Srilanka","Nepal","Myanmar",]
high_inflation_countries.sort(key=lambda countries:countries[1]) 

print(high_inflation_countries)

['Bangladesh', 'Nepal', 'India', 'Srilanka', 'Myanmar']

## Sets

### add

In [57]:
developed_countries={"Finland","Germany","Australia","France","USA"}
developed_countries.add("Russia")
print(developed_countries)

{'Russia', 'France', 'Germany', 'Finland', 'Australia', 'USA'}

### clear

In [60]:
developed_countries={"Finland","Germany","Australia","France","USA"}
developed_countries.clear()
print(developed_countries)

set()

### copy

In [66]:
developed_countries={"Finland","Germany","Australia","France","USA"}
countries=developed_countries.copy()
print(countries)

{'France', 'Germany', 'Finland', 'Australia', 'USA'}

### difference

In [104]:
## difference removes common element and returns remaining element in developed_countries

developed_countries={"Finland","Germany","Australia","France","USA"}
high_gdp_countries={"India","Japan","Germany","USA",}
developed_countries.difference(high_gdp_countries)

{'Australia', 'Finland', 'France'}

### difference_update

In [105]:
## same like difference but here it updates to the original list

developed_countries={"Finland","Germany","Australia","France","USA"}
high_gdp_countries={"India","Japan","Germany","USA",}
developed_countries.difference_update(high_gdp_countries)
print(developed_countries)

{'France', 'Finland', 'Australia'}

### discard

In [74]:
developed_countries={"Finland","Germany","Australia","France","USA"}
countries=developed_countries.discard("Finland")
print(developed_countries)

{'France', 'Germany', 'Australia', 'USA'}

### intersection

In [76]:
developed_countries={"Finland","Germany","Australia","France","USA"}
high_gdp_countries={"India","Japan","Germany","USA",}
countries=developed_countries.intersection(high_gdp_countries)
print(countries)

{'USA', 'Germany'}

### intersection_update

In [78]:
developed_countries={"Finland","Germany","Australia","France","USA"}
high_gdp_countries={"India","Japan","Germany","USA",}
developed_countries.intersection_update(developed_countries)
print(developed_countries)

{'France', 'Germany', 'Finland', 'Australia', 'USA'}

### isdisjoint

In [84]:
##isdisjoint: check whether no common elements are present.

developed_countries={"Finland","Germany","Australia","France","USA"}
high_gdp_countries={"India","Japan","Germany","USA",}
developed_countries.isdisjoint(high_gdp_countries)

False

### issubset

In [83]:
##issubset: check whether all the elements of setA are present in setB.

developed_countries={"Finland","Germany","Australia","France","USA"}
high_gdp_countries={"India","Japan","Germany","USA",}
developed_countries.issubset(high_gdp_countries)

False

### issuperset

In [87]:
## issuperset : checks whether all elements of a contains b

developed_countries={"Finland","Germany","Australia","France","USA"}
high_gdp_countries={"India","Japan","Germany","USA",}
developed_countries.issuperset(high_gdp_countries)

False

### pop

In [90]:
## here pop removes any random element

developed_countries={"Finland","Germany","Australia","France","USA"}
high_gdp_countries={"India","Japan","Germany","USA",}
developed_countries.pop()

'France'

### remove

In [92]:
developed_countries={"Finland","Germany","Australia","France","USA"}
developed_countries.remove("Finland")
developed_countries

{'Australia', 'France', 'Germany', 'USA'}

### symmetric_difference

In [95]:
##symmetric_difference : returns elements from either sets but not in both

developed_countries={"Finland","Germany","Australia","France","USA"}
high_gdp_countries={"India","Japan","Germany","USA",}
developed_countries.symmetric_difference(high_gdp_countries)

{'Australia', 'Finland', 'France', 'India', 'Japan'}

### union

In [96]:
developed_countries={"Finland","Germany","Australia","France","USA"}
high_gdp_countries={"India","Japan","Germany","USA",}
developed_countries.union(high_gdp_countries)

{'Australia', 'Finland', 'France', 'Germany', 'India', 'Japan', 'USA'}

### update

In [103]:
developed_countries={"Finland","Germany","Australia","France","USA"}
developed_countries.update(["Scotland"])
print(developed_countries)

{'France', 'Scotland', 'Germany', 'Finland', 'Australia', 'USA'}

## Tuple

### count

In [107]:
least_developed_countries=('southsudan','niger','nigeria','pakistan','cuba')
least_developed_countries.count("southsudan")

1

### index

In [111]:
least_developed_countries=('southsudan','niger','nigeria','pakistan','cuba')
least_developed_countries.index('nigeria')

2

## Dictionary

### clear

In [116]:
least_developed_countries={"southsudan":3,'niger':0.5,'nigeria':3.5,'pakistan':3,'cuba':4}
least_developed_countries.clear()
least_developed_countries

{}

### copy

In [119]:
least_developed_countries={"southsudan":3,'niger':0.5,'nigeria':3.5,'pakistan':3,'cuba':4}
poor_countries=least_developed_countries.copy()
poor_countries

{'southsudan': 3, 'niger': 0.5, 'nigeria': 3.5, 'pakistan': 3, 'cuba': 4}

### fromkeys & Update

In [127]:
least_developed_countries={"southsudan":3,'niger':0.5,'nigeria':3.5,'pakistan':3,'cuba':4}
new=least_developed_countries.fromkeys(["Iran","Iraq"],4)
least_developed_countries.update(new)
print(least_developed_countries)

{'southsudan': 3, 'niger': 0.5, 'nigeria': 3.5, 'pakistan': 3, 'cuba': 4, 'Iran': 4, 'Iraq': 4}

### get

In [129]:
least_developed_countries={"southsudan":3,'niger':0.5,'nigeria':3.5,'pakistan':3,'cuba':4}
least_developed_countries.get("pakistan")

3

### items

In [133]:
least_developed_countries={"southsudan":3,'niger':0.5,'nigeria':3.5,'pakistan':3,'cuba':4}
least_developed_countries.items()  ##items return it as a tuple

dict_items([('southsudan', 3), ('niger', 0.5), ('nigeria', 3.5), ('pakistan', 3), ('cuba', 4)])

### keys

In [134]:
least_developed_countries={"southsudan":3,'niger':0.5,'nigeria':3.5,'pakistan':3,'cuba':4}
least_developed_countries.keys()

dict_keys(['southsudan', 'niger', 'nigeria', 'pakistan', 'cuba'])

### pop

In [140]:
least_developed_countries={"southsudan":3,'niger':0.5,'nigeria':3.5,'pakistan':3,'cuba':4}
value=least_developed_countries.pop("niger")   ### here the pop removes the key, updates the dictionary, and returns the value
print(least_developed_countries)
print(value)

{'southsudan': 3, 'nigeria': 3.5, 'pakistan': 3, 'cuba': 4}
0.5

### popitem

In [143]:
least_developed_countries={"southsudan":3,'niger':0.5,'nigeria':3.5,'pakistan':3,'cuba':4}
least_developed_countries.popitem()  ### removes and returns the last item in the dictionary as a tuple

('cuba', 4)

### setdefault

In [150]:
least_developed_countries={"southsudan":3,'niger':0.5,'nigeria':3.5,'pakistan':3,'cuba':4}
least_developed_countries.setdefault("iran",2)
print(least_developed_countries)

{'southsudan': 3, 'niger': 0.5, 'nigeria': 3.5, 'pakistan': 3, 'cuba': 4, 'iran': 2}

### values

In [154]:
least_developed_countries={"southsudan":3,'niger':0.5,'nigeria':3.5,'pakistan':3,'cuba':4}
least_developed_countries.values()

dict_values([3, 0.5, 3.5, 3, 4])

# Task 2

## Dataframes using dictionaries

In [157]:
import pandas as pd
developed_countries={"Country_Name":["India","Germany","USA","Canada","England"],
                    "Growth%":[4,8,7,7,8],
                    "Inflation":[5.4,3,6,5,3]}
pd.DataFrame(data=developed_countries)

  Country_Name  Growth%  Inflation
0        India        4        5.4
1      Germany        8        3.0
2          USA        7        6.0
3       Canada        7        5.0
4      England        8        3.0

In [158]:
import pandas as pd
developed_countries={"Country_Name":["India","Germany","USA","Canada","England"],
                    "GDP":[4,8,7,7,8],
                    "Inflation":[5.4,3,6,5,3]}
pd.DataFrame(data=developed_countries)

  Country_Name  GDP  Inflation
0        India    4        5.4
1      Germany    8        3.0
2          USA    7        6.0
3       Canada    7        5.0
4      England    8        3.0

In [160]:
import pandas as pd
Parties={"Party_Name":["TVK","DMK","ADMK","INC","NTK"],
                    "Vote%":[3.48,3.1,3,2.73,1.35],
                    "Seats_Won":[108,73,54,4,0]}
pd.DataFrame(data=Parties)

  Party_Name  Vote%  Seats_Won
0        TVK   3.48        108
1        DMK   3.10         73
2       ADMK   3.00         54
3        INC   2.73          4
4        NTK   1.35          0